# fly.toml app configuration file generated for openrouter-mcp-tj on 2026-09-20T20:12:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openrouter-mcp-tj'
primary_region = 'sjc'

[build]
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
